name: Actualizar lista IPTV

on:
  schedule:
    - cron: '05 07 * * *'  # Todos los dÃ­as a las 09:05 hora de EspaÃ±a
    - cron: '05 08 * * *'  # Todos los dÃ­as a las 10:05 hora de EspaÃ±a
    - cron: '05 09 * * *'  # Todos los dÃ­as a las 11:05 hora de EspaÃ±a
    - cron: '05 10 * * *'  # Todos los dÃ­as a las 12:05 hora de EspaÃ±a
    - cron: '55 13 * * *'  # Todos los dÃ­as a las 15:55 hora de EspaÃ±a
    - cron: '05 15 * * *'  # Todos los dÃ­as a las 17:05 hora de EspaÃ±a
    - cron: '05 16 * * *'  # Todos los dÃ­as a las 18:05 hora de EspaÃ±a
    - cron: '05 17 * * *'  # Todos los dÃ­as a las 19:05 hora de EspaÃ±a
    - cron: '05 18 * * *'  # Todos los dÃ­as a las 20:05 hora de EspaÃ±a
    - cron: '05 19 * * *'  # Todos los dÃ­as a las 21:05 hora de EspaÃ±a
  workflow_dispatch:  # Permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  descarga_reemplazo:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
                  
      - name: Descargar archivo original
        run: |
          curl -L -f "https://ipfs.io/ipns/k2k4r8oqlcjxsritt5mczkcn4mmvcmymbqw7113fz2flkrerfwfps004/data/listas/lista_iptv.m3u" -o lista_original.m3u
          if [ ! -s lista_original.m3u ]; then
            echo "Error: El archivo descargado estÃ¡ vacÃ­o"
            exit 1
          fi
                  
      - name: Crear primera versiÃ³n modificada
        run: |
          sed 's/127.0.0.1:6878/acexy.taimado.qzz.io/g' lista_original.m3u | \
          sed 's/ *tvg-logo="https:\/\/www\.mxgp\.com\/sites\/default\/files\/news\/image\/logo%20Motors%20TV\.jpg"//g' > lista_modificada.m3u
          echo "âœ… Primera versiÃ³n creada: lista_modificada.m3u (acexy.taimado.qzz.io)"
                 
      - name: Crear segunda versiÃ³n modificada
        run: |
          sed 's/127.0.0.1:6878/192.168.102.254:6878/g' lista_original.m3u | \
          sed 's/ *tvg-logo="https:\/\/www\.mxgp\.com\/sites\/default\/files\/news\/image\/logo%20Motors%20TV\.jpg"//g' > lista_dispatcharr.m3u
          echo "âœ… Segunda versiÃ³n creada: lista_dispatcharr.m3u (192.168.102.254:6878)"
                          
      - name: Verificar si hay cambios
        id: verify_diff
        run: |
          git add lista_modificada.m3u lista_dispatcharr.m3u
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
                  
      - name: Commit y push de las listas modificadas
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "ðŸ¤– Lista M3U - $(TZ='Europe/Madrid' date +'%Y-%m-%d %H:%M:%S')"
          git push
