name: Actualizar lista IPTV

on:
  schedule:
    - cron: '05 11 * * *'  # Todos los dÃ­as a las 13:05 hora de EspaÃ±a
    - cron: '05 14 * * *'  # Todos los dÃ­as a las 16:05 hora de EspaÃ±a
    - cron: '17 11 * * *'  # Todos los dÃ­as a las 13:17 hora de EspaÃ±a
    - cron: '17 16 * * *'  # Todos los dÃ­as a las 18:17 hora de EspaÃ±a
    - cron: '17 17 * * *'  # Todos los dÃ­as a las 19:17 hora de EspaÃ±a
    - cron: '17 18 * * *'  # Todos los dÃ­as a las 20:17 hora de EspaÃ±a
  workflow_dispatch:      # Permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  descarga_reemplazo:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Descargar archivo original
        run: |
          curl -L -f "https://ipfs.io/ipns/k2k4r8oqlcjxsritt5mczkcn4mmvcmymbqw7113fz2flkrerfwfps004/data/listas/lista_iptv.m3u" -o lista_original.m3u
          if [ ! -s lista_original.m3u ]; then
            echo "Error: El archivo descargado estÃ¡ vacÃ­o"
            exit 1
          fi
        
      - name: Crear versiÃ³n con acestream://
        run: |
          sed 's|http://127\.0\.0\.1:6878/ace/getstream?id=|acestream://|g' lista_original.m3u > lista_acestream.m3u
          echo "âœ… VersiÃ³n creada: lista_acestream.m3u (con acestream://)"
        
      - name: Crear primera versiÃ³n modificada
        run: |
          sed 's/127.0.0.1:6878/192.168.1.57:6878/g' lista_original.m3u > lista_modificada.m3u
          echo "âœ… Primera versiÃ³n creada: lista_modificada.m3u (192.168.1.57:6778)"
        
      - name: Crear segunda versiÃ³n modificada
        run: |
          sed 's/127.0.0.1:6878/192.168.1.57:6878/g' lista_original.m3u > lista_ext.m3u
          echo "âœ… Segunda versiÃ³n creada: lista_ext.m3u (192.168.1.57:6888)"
        
      - name: Verificar si hay cambios
        id: verify_diff
        run: |
          git add lista_acestream.m3u lista_modificada.m3u lista_ext.m3u
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        
      - name: Commit y push de todas las listas modificadas
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "ðŸ¤– Lista M3U - $(TZ='Europe/Madrid' date +'%Y-%m-%d %H:%M:%S')"
          git push
